# Generated by Django 5.1.2 on 2024-12-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('phone_no', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('DoB', models.DateField()),
                ('subject', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=50)),
                ('father_phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin_code', models.CharField(max_length=6)),
                ('married_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=7)),
                ('qualification', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('blood_group', models.CharField(max_length=5)),
                ('DoB', models.DateField()),
                ('standard', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('father_name', models.CharField(max_length=50)),
                ('father_occupation', models.CharField(max_length=15)),
                ('mother_occupation', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_phone', models.CharField(max_length=10)),
                ('register_no', models.CharField(max_length=10)),
                ('father_phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin_code', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
            ],
        ),
    ]
