# Generated by Django 5.1.2 on 2024-12-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edulink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subject',
            field=models.CharField(default='General', max_length=10),
        ),
    ]
