# Generated by Django 5.1.2 on 2024-12-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edulink', '0002_alter_staff_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='father_phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(max_length=12),
        ),
    ]
