# Generated by Django 5.1.2 on 2024-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edulink', '0003_alter_staff_father_phone_alter_staff_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, choices=[('class teacher', 'Class Teacher'), ('subject teacher', 'Subject Teacher')], max_length=15, null=True),
        ),
    ]
