# Generated by Django 5.1.2 on 2024-12-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edulink', '0004_staff_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
