# Generated by Django 5.1.2 on 2024-12-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edulink', '0006_sign_up_v_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='v_code',
        ),
    ]
