# Generated by Django 5.1.2 on 2024-12-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edulink', '0007_delete_v_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
