# Generated by Django 5.1.2 on 2024-12-19 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edulink', '0008_alter_sign_up_password_alter_sign_up_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('DoB', models.DateField(verbose_name='Date of Birth')),
                ('blood_group', models.CharField(max_length=5, verbose_name='Blood Group')),
                ('married_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=10, verbose_name='Married Status')),
                ('phone_no', models.CharField(max_length=15, verbose_name='Phone No')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('father_name', models.CharField(max_length=50, verbose_name="Father's Name")),
                ('father_phone', models.CharField(max_length=15, verbose_name="Father's Phone")),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('position', models.CharField(max_length=100, verbose_name='Staff Position')),
                ('qualification', models.CharField(max_length=100, verbose_name='Qualification')),
                ('experience', models.IntegerField(verbose_name='Experience (Years)')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('pin_code', models.CharField(max_length=10, verbose_name='Pin Code')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff_images/', verbose_name='Profile Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff Members',
            },
        ),
    ]
