# Generated by Django 5.1.2 on 2024-12-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edulink', '0009_staffs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staffs',
        ),
    ]
