# Generated by Django 5.1.2 on 2024-12-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edulink', '0011_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
