# Generated by Django 5.1.2 on 2024-12-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edulink', '0013_assignment_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
