# Generated by Django 5.1.2 on 2024-12-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edulink', '0014_alter_assignment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
